server:
  port: 8082
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: user-status-check
          uri: lb://users-service
          predicates:
            - Path=/users-service/users/status/check
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RewritePath=/users-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: user-service-signup
          uri: lb://users-service
          predicates:
            - Path=/users-service/users
            - Method=POST
          filters:
            - RewritePath=/users-service/(?<segment>.*), /$\{segment}
        - id: user-service-login
          uri: lb://users-service
          predicates:
            - Path=/users-service/users/login
            - Method=POST
          filters:
            - RewritePath=/users-service/(?<segment>.*), /$\{segment}
        - id: user-service-get-update-delete
          uri: lb://users-service
          predicates:
            - Path=/users-service/users
            - Method=GET,PUT,DELETE
            - Header=Authorization, Bearer (.*)
          filters:
            - RewritePath=/users-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
  #      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    prefer-ip-address: true